-- Solved 15 challenges given by AI

--1. Finding the top-selling products by quantity.

select ProductID,ProductCategory,Quantity as Sold_Quantity from Tb1 order by Quantity desc;

--2. Identifying the customers with the highest total transaction amounts.

select top 15 CustomerID,ProductCategory,TotalAmount Total_Transaction from Tb1 order by TotalAmount desc

-- 3. Calculating the average transaction amount by payment method.

select PaymentMethod,avg(TotalAmount) Average_Transaction from Tb1 group by PaymentMethod

-- 4. Determining the most popular product categories.(By Number of Products)

select ProductCategory Popular_ProductCategory, count(ProductCategory) Product_Grand_Total from Tb1 
group by ProductCategory order by Product_Grand_Total desc

-- 5. Analyzing the sales performance of each store location.

Select top 10 StoreLocation, sum(TotalAmount) Sales_total from Tb1 
group by StoreLocation order by Sales_total desc

-- 6. Finding the customers who made multiple transactions on the same day.

select CustomerID from Tb1 group by CustomerID, TransactionDate having count(*)>1

-- 7. Calculating the total revenue generated by each product category.

select sum(TotalAmount) Total_Revenue, ProductCategory from Tb1 
group by ProductCategory 
order by Total_Revenue

-- 8. Identifying the customers who received the highest discounts.

select CustomerID, [DiscountApplied(%)] from Tb1 order by [DiscountApplied(%)] desc

-- 9. Analyzing the seasonal trends in transaction volume.

select datepart(quarter, TransactionDate) As Quarter,
count(*) as TransactionCount from Tb1
group by datepart(quarter, TransactionDate)
order by datepart(quarter, TransactionDate)

-- 10. Finding the top-selling products in each store location.

select sum(quantity) Sold_Products, ProductCategory, StoreLocation from Tb1 
group by StoreLocation, ProductCategory
order by Sold_Products desc

-- 11. Calculating the average price per unit for each product category.

select avg(Price) Average_price, ProductCategory from Tb1
group by ProductCategory
order by Average_price

-- 12. Identifying the most common payment methods used by customers.


select count(PaymentMethod) Top_Payment_method,PaymentMethod from Tb1
group by PaymentMethod
order by Top_Payment_method

-- 13. Analyzing the correlation between quantity and price for each product.

SELECT 
    ProductID,
    (SUM(Quantity * price) - SUM(Quantity) * SUM(Price) / COUNT(*)) / 
    (SQRT((SUM(Quantity * Quantity) - SUM(Quantity) * SUM(Quantity) / COUNT(*)) * 
    (SUM(Price * Price) - SUM(Price) * SUM(Price) / COUNT(*)))) AS Correlation
FROM 
    Tb1
GROUP BY 
    ProductID;

--	or 

select ProductID, correlation(Quantity, Price) from tb1
group by ProductCategory

-- 14. Determining the average discount percentage applied to transactions.

select round(avg([DiscountApplied(%)]), 3) Average_Discounts from Tb1 

-- 15. Analyzing the distribution of transaction dates throughout the year.


select datepart(year, TransactionDate) Year, 
datepart(Month, TransactionDate) Month,
count (*) Number_of_transactions
from Tb1
group by 
datepart(year, TransactionDate),
datepart(Month, TransactionDate)
order by
datepart(year, TransactionDate),
datepart(Month, TransactionDate)
